import { xml2js } from 'xml-js';

export type ODataVersion = 'V2' | 'V3' | 'V4' | 'Unknown';

interface EntityType {
  name: string;
  keys: string[];
  properties: { name: string; type: string }[];
  navigationProperties: { name: string; toRole?: string; relationship?: string; type?: string }[];
}

interface Association {
  name: string;
  ends: { role: string; type: string; multiplicity: string }[];
}

// 1. OData 检测与版本识别
export const detectODataVersion = async (url: string): Promise<ODataVersion> => {
  try {
    const metadataUrl = url.endsWith('$metadata') ? url : `${url.replace(/\/$/, '')}/$metadata`;
    const response = await fetch(metadataUrl);
    const text = await response.text();
    
    if (text.includes('Version="4.0"')) return 'V4';
    if (text.includes('Version="2.0"')) return 'V2';
    if (text.includes('Version="3.0"')) return 'V3';
    
    // 某些 V2 服务可能在 Header 里的 DataServiceVersion
    const versionHeader = response.headers.get('DataServiceVersion');
    if (versionHeader?.startsWith('2.0')) return 'V2';
    
    return 'Unknown';
  } catch (e) {
    console.error("Failed to detect OData version", e);
    return 'Unknown';
  }
};

// 2. 解析 Metadata (简化版，用于提取 ER 图所需信息)
export const parseMetadataToSchema = (xmlText: string) => {
  const result = xml2js(xmlText, { compact: true }) as any;
  const schemas = result['edmx:Edmx']?.['edmx:DataServices']?.['Schema'];
  // 处理可能有多个 Schema 的情况
  const schema = Array.isArray(schemas) ? schemas[0] : schemas;
  
  if (!schema) return { entities: [], associations: [] };

  const entities: EntityType[] = [];
  const associations: Association[] = [];

  const entityTypes = Array.isArray(schema.EntityType) ? schema.EntityType : [schema.EntityType].filter(Boolean);
  const assocTypes = Array.isArray(schema.Association) ? schema.Association : [schema.Association].filter(Boolean);

  // 解析实体
  entityTypes.forEach((et: any) => {
    const props = Array.isArray(et.Property) ? et.Property : [et.Property].filter(Boolean);
    const keys = et.Key ? (Array.isArray(et.Key.PropertyRef) ? et.Key.PropertyRef.map((k: any) => k._attributes.Name) : [et.Key.PropertyRef._attributes.Name]) : [];
    const navProps = et.NavigationProperty ? (Array.isArray(et.NavigationProperty) ? et.NavigationProperty : [et.NavigationProperty]) : [];

    entities.push({
      name: et._attributes.Name,
      keys,
      properties: props.map((p: any) => ({ name: p._attributes.Name, type: p._attributes.Type })),
      navigationProperties: navProps.map((np: any) => ({
        name: np._attributes.Name,
        relationship: np._attributes.Relationship, // V2
        toRole: np._attributes.ToRole, // V2
        type: np._attributes.Type // V4
      }))
    });
  });

  // 解析关联 (V2/V3)
  assocTypes.forEach((at: any) => {
    const ends = Array.isArray(at.End) ? at.End : [at.End];
    associations.push({
      name: at._attributes.Name,
      ends: ends.map((e: any) => ({
        role: e._attributes.Role,
        type: e._attributes.Type,
        multiplicity: e._attributes.Multiplicity
      }))
    });
  });

  return { entities, associations, namespace: schema._attributes.Namespace };
};

// 3. SAPUI5 代码生成器
export const generateSAPUI5Code = (
  operation: 'read' | 'create' | 'update' | 'delete',
  entitySet: string,
  params: any,
  version: ODataVersion
) => {
  const isV4 = version === 'V4';

  if (operation === 'read') {
    const { filters, sorters, expand, select, top, skip, inlinecount } = params;
    
    // 构建 Filters 代码字符串
    const filterCode = filters && filters.length > 0 
      ? `[\n    ${filters.map((f: any) => `new sap.ui.model.Filter("${f.field}", sap.ui.model.FilterOperator.${f.operator}, "${f.value}")`).join(',\n    ')}\n  ]` 
      : '[]';

    // 构建 Sorters 代码字符串
    const sorterCode = sorters && sorters.length > 0
      ? `[\n    ${sorters.map((s: any) => `new sap.ui.model.Sorter("${s.field}", ${s.descending})`).join(',\n    ')}\n  ]`
      : '[]';

    // URL 参数
    const urlParamsObj: string[] = [];
    if (expand) urlParamsObj.push(`"$expand": "${expand}"`);
    if (select) urlParamsObj.push(`"$select": "${select}"`);
    if (top) urlParamsObj.push(`"$top": ${top}`);
    if (skip) urlParamsObj.push(`"$skip": ${skip}`);
    if (inlinecount) urlParamsObj.push(isV4 ? `"$count": true` : `"$inlinecount": "allpages"`);

    return `// 带查询选项的读取 - Generated by OData Master
oModel.read("/${entitySet}", {
  filters: ${filterCode},
  sorters: ${sorterCode},
  urlParameters: {
    ${urlParamsObj.join(',\n    ')}
  },
  success: function(oData) {
    console.log("Success:", oData);
  },
  error: function(oError) {
    console.error("Error:", oError);
  }
});`;
  }

  if (operation === 'delete') {
    const key = params.key; // 假设传入的是组装好的 key 字符串 e.g. (ID=1)
    return `// 删除操作 - Generated by OData Master
oModel.remove("/${entitySet}${key}", {
  success: function() {
    console.log("Deleted successfully");
  },
  error: function(oError) {
    console.error("Delete failed:", oError);
  }
});`;
  }

  if (operation === 'update') {
    const { key, data } = params;
    return `// 更新操作 - Generated by OData Master
var oData = ${JSON.stringify(data, null, 2)};
oModel.update("/${entitySet}${key}", oData, {
  success: function() {
    console.log("Updated successfully");
  },
  error: function(oError) {
    console.error("Update failed:", oError);
  }
});`;
  }

  if (operation === 'create') {
    const { data } = params;
    return `// 新增操作 - Generated by OData Master
var oData = ${JSON.stringify(data, null, 2)};
oModel.create("/${entitySet}", oData, {
  success: function(oCreatedEntry) {
    console.log("Created successfully:", oCreatedEntry);
  },
  error: function(oError) {
    console.error("Create failed:", oError);
  }
});`;
  }

  return '// Unknown operation';
};